<?php 
define('HELLOASSO_WOOCOMMERCE_CLIENT_ID_TEST', 'f0d81e4e223147e69da871fe1706a162');
define('HELLOASSO_WOOCOMMERCE_CLIENT_SECRET_TEST', 'ynSQwxehkC9fELGDvSmQo+FsL3CZDIhY');
define('HELLOASSO_WOOCOMMERCE_API_URL_TEST', 'https://api.helloasso-sandbox.com/');
define('HELLOASSO_WOOCOMMERCE_AUTH_URL_TEST', 'https://auth.helloasso-sandbox.com/');

define('HELLOASSO_WOOCOMMERCE_CLIENT_ID_PROD', 'f0d81e4e223147e69da871fe1706a162');
define('HELLOASSO_WOOCOMMERCE_CLIENT_SECRET_PROD', 'ynSQwxehkC9fELGDvSmQo+FsL3CZDIhY');
define('HELLOASSO_WOOCOMMERCE_API_URL_PROD', 'https://api.helloasso.com/');
define('HELLOASSO_WOOCOMMERCE_AUTH_URL_PROD', 'https://auth.helloasso.com/');